### ISSUE TITLE
Not sure how to paste into OW

### ISSUE THREAD

**Issue by coolq1000** [ItsDeltin/Overwatch-Script-To-Workshop#1]
Hi,

Thank you for this amazing tool!

The code compiles fine, however, I'm completely stumped on how to paste the code into overwatch?
It is worth noting that the code is successfully copied into my clipboard, when I go to paste it in OW it just doesn't paste :/

Thanks.

**Comment by ItsDeltin** [comment]
Is there any error message in the chat when you paste? Try pasting into notepad, is the code being copied correctly? Are you on PTR for the latest release?

**Comment by coolq1000** [comment]
When I paste absolutely nothing happens, did you say I needed to be on the PTR?

**Comment by ItsDeltin** [comment]
The latest release "PTR support, instant script compilation" is for the new ptr update, "OSTW v0.1.3" works on live.
