### ISSUE TITLE
Conditional error

### ISSUE THREAD

**Issue by Eruru3510** [ItsDeltin/Overwatch-Script-To-Workshop#101]
![27CD5ZF@FLKW8PPQZ68XBQR](https://user-images.githubusercontent.com/35144004/73308011-4a581d80-425a-11ea-8ea7-06ea2fc2c022.png)
![G $S1_53NT$V%E%KVTFOH8I](https://user-images.githubusercontent.com/35144004/73308064-6a87dc80-425a-11ea-907e-3701827df0bd.png)

**Comment by ItsDeltin** [comment]
Looks like an optimizing error, disable `Optimize Output` in the settings.

**Comment by Eruru3510** [comment]
Problem solved, thank you very much

**Comment by TrueCP6** [comment]
Probably a problem with `EqualTo`.
