### ISSUE TITLE
Compiler throws expected EOF error when last line a comment

### ISSUE THREAD

**Issue by pielover928** [ItsDeltin/Overwatch-Script-To-Workshop#107]
if the last line is a comment, like so:
```
code;
code;
//comment
```

The compiler will throw an error:
`Error at 186, 0: extraneous input '/' expecting {<EOF>, DOCUMENTATION, 'rule', 'define', 'globalvar', 'playervar', 'struct', 'class', 'private', 'public', 'static', 'macro', 'disabled', 'enum', 'ref', 'method', PART}`

**Comment by ItsDeltin** [comment]
Fixed in [v1.5](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.5).
