### ISSUE TITLE
Can't Use <"Ability 1 <0>", EnabledAbility1>

### ISSUE THREAD

**Issue by Eruru3510** [ItsDeltin/Overwatch-Script-To-Workshop#11]

**Comment by ItsDeltin** [comment]
Thanks for the report! There seems to be a bug with strings containing numbers, it will be fixed next release.
The following strings are broken:
Ability 1
Ability 2
Use Ability 1
Use Ability 2

Right now for a workaround, you can do <"ability <0> <1>", 1, EnabledAbility1> which will result in the same string.

**Comment by Eruru3510** [comment]
I am using your tool to make my game mode, the tools you make are great.

**Comment by ItsDeltin** [comment]
Fixed in v0.3.
