### ISSUE TITLE
Pathmaps cannot be converted to Ow Workshop Code

### ISSUE THREAD

**Issue by LionariusPy** [ItsDeltin/Overwatch-Script-To-Workshop#111]
![image](https://user-images.githubusercontent.com/45388086/76313995-10f9df80-62e7-11ea-9c0c-d41b1fd818b9.png)
Thats what it says when im trying to convert pathmaps

**Comment by ItsDeltin** [comment]
I am having trouble reproducing the error. Does it occur when converting `.csv` files to `.pathmap` files? Or does it occur when creating a `Pathmap` object in code?

**Comment by LionariusPy** [comment]
It occurs when u drop .pathmap file into Deltinteger.exe

**Comment by ItsDeltin** [comment]
You need to make a script to use pathfinding.
```js
globalvar Pathmap hanamura = new Pathmap("!hanamura.pathmap")
playervar define pathfindTo = null;

rule: "Do pathfind."
Event.OngoingPlayer
if (pathfindTo != null)
{
    hanamura.Pathfind(EventPlayer, pathfindTo);
}
```
If you don't want to use OSTW for your project and you just want to paste pathfinding stuff into an existing project, add this on the top of the script to prevent variable name conflicts when pasting in:
```js
globalvar {
    "A global variable",
    "A player variable."
    // Variable IDs
    0,
    1,
    2
}
playervar {
}
```

**Comment by LionariusPy** [comment]
Ok, maybe I gave bad title for this issue. Let me explain it better. I have a .pathmap file and i want to edit it, to do that I follow the instruction on wiki page "Pathfinding" - "Editing .pathmap file". It says that I should drop .pathmap file into Deltinteger.exe, but when I do that screenshotted error occurs.

**Comment by ItsDeltin** [comment]
You are fine, I just forgot you could do that. The Assets section of the 1.2 release now has a new file `1.2.1.zip` which contains the fix. Thanks for reporting!
