### ISSUE TITLE
Idea: Implement types for everything.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#118]
An idea is create an typed language, like Vector type.

Also for
- Number
- Player
- ...

For example all relative to player in Player type, for example.
✅ `hostPlayer.Damage(null, eventPlayer.MaxHealth)`
❌ `Damage(Host Player(), null, Max Health(Event Player()))`

**Comment by ItsDeltin** [comment]
#119
