### ISSUE TITLE
Idea: Implement types for everything.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#119]
An idea is create an typed language, like Vector type.

Implement types for Number, Boolean, Player, Variable, etc.

For example all relative to player in Player type, for example.
✅ `hostPlayer.Damage(null, eventPlayer.MaxHealth)`
❌ `Damage(HostPlayer(), null, MaxHealth(EventPlayer()))`

For example number types:
- `globalvar number gameTime;`
- `gameTime.Abs()`
- `gameTime.Sqrt()`
etc.

✅ `eventPlayer.DisallowButton(Button.Interact);`
❌ `DisallowButton(EventPlayer(), Button.Interact)`

```cs
rule "detect dead players": 
Event.OngoingPlayer
if(eventPlayer.IsAlive) // IsAlive is boolean property from Player type.
{
}
```

But keep some functions like:
✅ `SmallMessage(AllPlayers(), "hello world")`
✅ `eventPlayer.SmallMessage("hello world");`
⚠️ `[eventPlayer, hostPlayer].SmallMessage("hello world"); // Array of player, translated to "append to array" and "empty array" in smallmessage action`

**Comment by ItsDeltin** [comment]
Implementing this would make solving #125 easier.

**Comment by ItsDeltin** [comment]
v2.0-beta.8 :)
