### ISSUE TITLE
Pathfinding algorithm bug

### ISSUE THREAD

**Issue by LionariusPy** [ItsDeltin/Overwatch-Script-To-Workshop#120]
Pathfinding algorithm creates wrong path after first run. If it hits node at Nodes[0] it stops calculating path. Better explanation at screenshots.

Pathmap(Node at Nodes[0] marked with arrow):
![image](https://user-images.githubusercontent.com/45388086/76436932-e0d73d00-63c9-11ea-9e9a-9a53334a4310.png)
First run:
![image](https://user-images.githubusercontent.com/45388086/76435846-96a18c00-63c8-11ea-98a8-a4d9163e0f45.png)
Next runs:
![image](https://user-images.githubusercontent.com/45388086/76435924-ac16b600-63c8-11ea-9b62-e33c2072e946.png)

**Comment by LionariusPy** [comment]
Just noticed that pathfinding algorithms appends 0 to path and then stops
![image](https://user-images.githubusercontent.com/45388086/76437134-285dc900-63ca-11ea-90ec-488b2297a370.png)

**Comment by LionariusPy** [comment]
Just noticed that Dijkstra_Current becomes -2 and 0 appends to final path

**Comment by ItsDeltin** [comment]
Looks like a pathfinding variable isn't getting reset correctly after running the algorithm.

**Comment by ItsDeltin** [comment]
v1.2.2 fixes this, it is at the bottom of the 1.2 release.
