### ISSUE TITLE
AllTankHeroes, AllSupportHeroes and AllDamageHeroes are missing

### ISSUE THREAD

**Issue by MichaelBrunn3r** [ItsDeltin/Overwatch-Script-To-Workshop#127]
As the title says, equivalent methods for the Workshop Actions "All Tank Heroes", "All Support Heroes" and "All Damage Heroes" are missing.
These are quite important for filtering for Hero type.

**Comment by ItsDeltin** [comment]
Added in [v1.3](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.3).
