### ISSUE TITLE
Built-in variables (extended collection and array builder) are created, even when not used at all.

### ISSUE THREAD

**Issue by MichaelBrunn3r** [ItsDeltin/Overwatch-Script-To-Workshop#131]
Currently variables "_extendedGlobalCollection", "_arrayBuilder", "Nodes", "Segments" and "_extendedPlayerCollection" are created even if the project never uses them. It would be great if the compiler only creates them if necessary, either by automatic optimization or a compiler instruction.

This could be expanded to custom variables as well. Currently every declared variable is exported, even if not used.

**Comment by ItsDeltin** [comment]
There should additionally be a warning when a variable is unused.
Related to #112.

**Comment by ItsDeltin** [comment]
`Nodes` and `Segments` is no longer created in v1.3.

**Comment by ItsDeltin** [comment]
Done in v2.0
