### ISSUE TITLE
Weird behavior with multiple instances of different classes

### ISSUE THREAD

**Issue by quantiom** [ItsDeltin/Overwatch-Script-To-Workshop#134]
I've been having issues with using multiple classes that have the same names for the variables. (although I believe the names don't matter)

Here is an example:
```
class Test {
    public Vector location;
    public define somethingElse;

    public Test(Vector loc, define something) {
        this.location = loc;
        this.somethingElse = something;
    }
}

class Test2 {
    public Vector location;
    public define somethingElse;

    public Test(Vector loc, define something) {
        this.location = loc;
        this.somethingElse = something;
    }
}

globalvar Test test = new Test(Vector(150.0, 50.0, 0.0), 50);
globalvar Test2 test2 = new Test2(Vector(0.0, 0.0, 0.0), 123);

rule: "Print values"
Event.OngoingPlayer
if (IsButtonHeld(EventPlayer(), Button.Interact)) {
    SmallMessage(EventPlayer(), <"test num: <0>", test.somethingElse>);
    SmallMessage(EventPlayer(), <"test2 num: <0>", test2.somethingElse>);
}
```

I would expect "test num: 50" to be printed, but "test num: 0" is printed. The other one prints "test num: 123", which works as expected. However, when I comment out the declaration of `test2`, `test.somethingElse` is 50 again.

In my other script, the last instance of a class would replace the ones before it with its properties, which was also really weird.

**Comment by TrueCP6** [comment]
Your problem is that `Test2`s constructor is `Test` which should result in an error. If you fix that it should work as intended.

**Comment by quantiom** [comment]
Sorry, that was a typo. Even if you change it to `Test2`, it is the same.

**Comment by quantiom** [comment]
Seems like the bug was using `this`: https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/issues/135.
