### ISSUE TITLE
Output error

### ISSUE THREAD

**Issue by Kikugie** [ItsDeltin/Overwatch-Script-To-Workshop#136]
I have a
`Error:
  An assembly specified in the application dependencies manifest (Deltinteger.deps.json) was not found:
    package: 'Microsoft.Win32.SystemEvents', version: '4.6.0'
    path: 'runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll'
[Info  - 20:11:32] Connection to server got closed. Server will restart.` five times
as output in overwatch script to workshop and no output in workshop code.

**Comment by ItsDeltin** [comment]
I haven't seen this error before and I haven't been able to reproduce it.
- Does the file `runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll` exist in your OSTW folder?
- Something may be wrong with your dotnet core runtime installation.
- What is your operating system?

**Comment by Kikugie** [comment]
I'm using Windows 10. It looks like .NET Core has broken down or is outdated since I last used it, so I reinstalled it and now it works. Thanks
