### ISSUE TITLE
Syntax error when using "Team." In rule definition

### ISSUE THREAD

**Issue by sarami77** [ItsDeltin/Overwatch-Script-To-Workshop#143]
When using "Team." In the rule definition in the VScode editor, WorkShopCode outputs an "Error not an expected enum" and no code is generated.

This problem occurs with the following combinations:
[OSTW v1.3]
  -Deltinteger_v1.3
  -overwatch-script-to-workshop-1.4.0.vsix

It has been confirmed that it does not occur in the following combinations.
  [OSTW v1.2]
  -Deltinteger_v1.2.2
  -overwatch-script-to-workshop-1.3.0.vsix

I don't think there is a change in the Team syntax specification. Is it a bug?
This may be the effect of the #121 fix.
If necessary, we can provide more information needed for the investigation.

Thank you for your work.

**Comment by sarami77** [comment]
I attach a snapshot when the problem occurred
![snapshot](https://user-images.githubusercontent.com/63502714/79045356-9f92b100-7c45-11ea-919e-418d936b93c2.png)

**Comment by ItsDeltin** [comment]
A workaround for now would be to add `TeamOf(EventPlayer()) == Team.Team1/2`

**Comment by sarami77** [comment]
thank for your reply.
I'll give it a try.

**Comment by ItsDeltin** [comment]
Fixed in [v1.4](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.4).
