### ISSUE TITLE
v1.4.1 - Paste error occurs in the definition of the array that stores enum

### ISSUE THREAD

**Issue by sarami77** [ItsDeltin/Overwatch-Script-To-Workshop#147]
With the update from v1.2 to v1.4.1, the output code of the array definition has changed.
However, this is a paste error in OW WorkShop (ver1.47.1.0.68126 latest as of 2020/4/28).

Is this a bug?
Or is it supposed to change the format of WorkShop code implemented in PTR?

**Comment by sarami77** [comment]
[Definition code & Generated code]
![snapshot](https://user-images.githubusercontent.com/63502714/80451520-08c13680-895f-11ea-8195-6f9333927060.png)

[Erorr in OW WorkShop]
![snapshot2](https://user-images.githubusercontent.com/63502714/80451518-07900980-895f-11ea-80db-4f4f6384c2e6.png)

**Comment by sarami77** [comment]
An interim workaround is to nest Append To Array as ver v1.2

**Comment by ItsDeltin** [comment]
It pastes fine for me, are you on the PTR?

**Comment by sarami77** [comment]
No, I play on offcial Server. not PTR.
Is the change from v1.2 to v1.4.1 premised on using PTR?
If so, this issue has been created incorrectly.

**Comment by ItsDeltin** [comment]
Arrays in 1.4 uses the workshop's new `Array` value, which is only on the ptr right now. It saves a lot of element space :)

**Comment by sarami77** [comment]
I understand. I will waiting for the official implementation from the PTR of the OW client.
Probably # 149 may be the same...
Thank you for your hard work!
