### ISSUE TITLE
v1.4.1 - Incorrect character string replacement

### ISSUE THREAD

**Issue by sarami77** [ItsDeltin/Overwatch-Script-To-Workshop#148]
With the update from v1.2 to v1.4.1, generate incorrect code about the output code of string replacement.
The fourth replacement parameter [reviveTimeLimit] is lost and replaced by a [Help] literal instead.

![snapshot](https://user-images.githubusercontent.com/63502714/80453661-adde0e00-8963-11ea-81cf-83498afc5078.png)

**Comment by ItsDeltin** [comment]
Thanks for the report, there is a bug when using more than 3 format parameters.

**Comment by sarami77** [comment]
I confirmed fixed this issue by OSTW v1.5.
closed this issue.
