### ISSUE TITLE
v1.4.1 - Paste error occurs in empty array difinition

### ISSUE THREAD

**Issue by sarami77** [ItsDeltin/Overwatch-Script-To-Workshop#149]
With the update from v1.2 to v1.4.1, the output code of the empty array definition has changed.
However, this is a paste error in OW WorkShop (ver1.47.1.0.68126 latest as of 2020/4/28).
![snapshot](https://user-images.githubusercontent.com/63502714/80454995-ea126e00-8965-11ea-88e1-63232ec7103e.png)

This problem can be easily avoided by replacing "[]" with "EmptyArray ()".

**Comment by sarami77** [comment]
I play on offcial Server. not PTR.
Is the change from v1.2 to v1.4.1 premised on using PTR?
If so, this issue has been created incorrectly.

**Comment by sarami77** [comment]
I understand. I will waiting for the official implementation from the PTR of the OW client.
Probably # 149 may be the same...
Thank you for your hard work !

**Comment by effyn** [comment]
I've been unable to reproduce this. Closing this issue is probably best

**Comment by sarami77** [comment]
This issue happen by used old OW client.
Not happen because PTR change released.
I close this issue.
