### ISSUE TITLE
Add a way to allow ref parameters to be modified within methods

### ISSUE THREAD

**Issue by DMRogue** [ItsDeltin/Overwatch-Script-To-Workshop#150]
This may be intentional, but I've found that `ref` parameters cannot be set to.
```
void method(ref define x)
{
  x = 1
}
```
This gives back the error `The variable 'x' cannot be set to.`

Is this intentional?
If so, is there a way to pass and modify a variable from a method?

**Comment by TrueCP6** [comment]
This is completely intentional. If you want to modify a parameter variable it should be a normal `define varname` parameter.

**Comment by ItsDeltin** [comment]
There should be a way to directly take variables that can be used with `ModifyVariable`, `ChaseVariable`,  or be set to.

**Comment by ItsDeltin** [comment]
With lambdas, you can do something like:
```
void method(BlockLambda<define> setX)
{
  setX.Invoke(1);
}

// Call it like:
method(define value => { x = value })
```

**Comment by ItsDeltin** [comment]
Added in v2.0
