### ISSUE TITLE
Enum auto complete not working

### ISSUE THREAD

**Issue by TforTrevor** [ItsDeltin/Overwatch-Script-To-Workshop#168]
When typing in an enum, the enum's values do not auto complete and instead shows every available workshop variable and action.

![image](https://user-images.githubusercontent.com/36804391/87835476-3c737480-c85b-11ea-934d-f8dbce75682e.png)

**Comment by ItsDeltin** [comment]
The completion seems to be handled before the dot is. Closing the completion window then pressing Ctrl+space should show the correct results.

**Comment by TforTrevor** [comment]
My bad, I haven't used this in a while and forgot you had to ctrl+space a lot to get completion to show up. 
Out of curiosity, is there no way for it to show proper suggestions without the ctrl+space combination?

**Comment by ItsDeltin** [comment]
I can fix it. This bug appeared in the last update, v1.6.

**Comment by ItsDeltin** [comment]
Fixed in [v1.7](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.7).
