### ISSUE TITLE
Language Server Crash

### ISSUE THREAD

**Issue by LollerMann** [ItsDeltin/Overwatch-Script-To-Workshop#170]
Here's the log file. I don't know what else I'm supposed to provide here
[log20200830.txt](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/files/5147034/log20200830.txt)

**Comment by ItsDeltin** [comment]
Thanks for the log! It seems that the crash occurs when there is a parser exception when initially loading a file.

If some script elements are missing (for example, unbalanced parentheses), it may cause the parser to crash, for example:

```
rule: "A"
{
    SmallMessage(
}
```

The 'Workshop Code' tab will show the current parser exception. You can comment out your code until you narrow down where the error is happening.

This is a *very very* big problem and I plan to have the next update address this.

**Comment by UniqueUname** [comment]
Yup, I forgot to close one parantheses. Thanks for clarifying it out. should I close this issue?

**Comment by ItsDeltin** [comment]
Nope, I will leave the issue open until the bugs related to this issue is fixed.
