### ISSUE TITLE
decompiling a game mode with custom settings will not include rules

### ISSUE THREAD

**Issue by darmanilink** [ItsDeltin/Overwatch-Script-To-Workshop#172]
The target .del file only includes the import.

**Comment by darmanilink** [comment]
https://pastebin.com/y8M0qbuR

For a ready made test file

**Comment by ItsDeltin** [comment]
Thank you! This will be fixed next release.

**Comment by Polymathical** [comment]
I'm not sure my fix is appropriate if the data center list changes. Is there support for a non-determinant value list?

**Comment by Protowalker** [comment]
I don't believe there is right now, but it should be possible to build in regex or something similar to the schema. Is anyone able to provide more examples so that any pattern matching can be more exhaustive?
