### ISSUE TITLE
maybe need nested variable

### ISSUE THREAD

**Issue by Eruru3510** [ItsDeltin/Overwatch-Script-To-Workshop#19]
"define playervar SavedOtherPlayer;
define playervar HealAmount;" then know index is 0

"ValueInArray (PlayerVariable (SavedOtherPlayer, Variable.A), 0)" get SavedOtherPlayer's HealAmount

maybe can use "SavedOtherPlayer.HealAmount" Instead of just "EventPlayer ().HealAmount"

**Comment by ItsDeltin** [comment]
Sorry if I misunderstood, but you can already do this.
```
define playervar isDva;

rule: "Player Variables"
{
    define playersPlayingDva = PlayersOnHero(Hero.Dva);
    playersPlayingDva.isDva = true;
}
```
