### ISSUE TITLE
"EvaulateOnce()" doesn't return its parameter's value

### ISSUE THREAD

**Issue by Protowalker** [ItsDeltin/Overwatch-Script-To-Workshop#210]
Assuming that `test` is a class that a field "color":
`EvaluateOnce(test).color` seems like it should work, but it returns an error.
`EvaluateOnce(test.color)` wraps the entire expression, meaning color won't reevaluate.
The current workaround is `(<Test>EvaluateOnce(test)).color` but the first syntax seems most fitting to me.

**Comment by Protowalker** [comment]
`(<Test>EvaluateOnce(test)).color` also doesn't seem to work. It gives the error `Invalid Expression Term ')'` just before the dot.

**Comment by Protowalker** [comment]
Just checked and it is apparently caused by the typecast operator.

**Comment by ItsDeltin** [comment]
Done in v2.0
