### ISSUE TITLE
Incorrect output values for enums

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#213]
`Button.Interact` becomes `Button(Interact)` while it should be `Interact`. This also happens with the colour enum.

**Comment by Protowalker** [comment]
Are you on live or PTR? the preview is for PTR, where this is proper behavior.

**Comment by TrueCP6** [comment]
I was on live using the preview. It works correctly in the PTR.

**Comment by Protowalker** [comment]
Lol, happens to the best of us! Honestly at this scope I'd personally rather some false positives over false negatives when it comes to issue reports
