### ISSUE TITLE
Decompiling fails on 2.0-preview-b

### ISSUE THREAD

**Issue by Andygmb** [ItsDeltin/Overwatch-Script-To-Workshop#215]
Decompiling on 2.0-preview-b with the following clipboard script results in the error below.

[clipboard.txt](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/files/5498637/clipboard.txt)

```
SuccessEnd of file not reached, stuck at: 'enabled heroes
			{
				Baptiste
			}
		}
	}
'
```

if you remove the settings block (clipboard_nosettings.txt), as #172 indicates may be causing issues, you get the following error:

[clipboard_nosettings.txt](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/files/5498657/clipboard_nosettings.txt)

```
SuccessEnd of file not reached, stuck at: 'White, White,
			White, Visible To and String, De'

```

**Comment by Protowalker** [comment]
Are you decompiling from the extension or from the command line?

**Comment by Andygmb** [comment]
From the visual studio extension
