### ISSUE TITLE
Completion Range for arrays/invokes in parameters extends too far

### ISSUE THREAD

**Issue by Soulless-Me** [ItsDeltin/Overwatch-Script-To-Workshop#217]
Extension Version: `2.2.0`

Deltinteger Version: `2.0 preview B`

![11](https://user-images.githubusercontent.com/74082054/98673562-693e2100-234f-11eb-9cc7-84dfb25fbb5b.gif)

**Comment by Protowalker** [comment]
Alright, this problem appears to be a little deeper than originally thought. It appears that method calls don't end their range at the right mark.
