### ISSUE TITLE
"Event." autocomplete broken?

### ISSUE THREAD

**Issue by Soulless-Me** [ItsDeltin/Overwatch-Script-To-Workshop#218]
![1 7](https://user-images.githubusercontent.com/74082054/98748777-44c76080-23b2-11eb-8f16-1ff7e80a9adb.png)
![2pb](https://user-images.githubusercontent.com/74082054/98748780-45f88d80-23b2-11eb-825f-22da15c87cf6.png)

**Comment by Protowalker** [comment]
It looks like all enums are broken; are you compiling from source or did you just download the preview?

**Comment by Soulless-Me** [comment]
> It looks like all enums are broken; are you compiling from source or did you just download the preview?

Yes, I did that

**Comment by Protowalker** [comment]
It looks like the fix for #217 caused this. Let me take a minute to fix it.

**Comment by Protowalker** [comment]
Closing this and renaming #217
