### ISSUE TITLE
2.0 Preview B Game Settings Not Compiling Correctly

### ISSUE THREAD

**Issue by Jordan-Ireland** [ItsDeltin/Overwatch-Script-To-Workshop#221]
When compiling Deathmatch `Game Length In Minutes`, it doesn't compile correctly. It puts in a % when it should just be a number.

Example:
## JSON File
```
"Modes": {
    "Deathmatch": {
      "Enabled Maps": [
        "Workshop Island"
      ]
      "Game Length In Minutes": 14
    }
  }
```

## Workshop Output
```
Deathmatch
        {
            Game Length In Minutes: 14%
            enabled maps
            {
                Workshop Island
            }
        }
```

## Expected Output
```
Deathmatch
        {
            Game Length In Minutes: 14
            enabled maps
            {
                Workshop Island
            }
        }
```

**Comment by Protowalker** [comment]
Your JSON file doesn't seem to be valid; that won't fix this issue but if you can give a valid one it'll help more with testing.

**Comment by Protowalker** [comment]
UPDATE: the problem was on my end; give me one sec to fix this linux bug and then I'll work on this for you.

**Comment by Jordan-Ireland** [comment]
> UPDATE: the problem was on my end; give me one sec to fix this linux bug and then I'll work on this for you.

I could upload the entire JSON file that is working besides that one line if that would help? Also, off topic when would an update for the new overwatch update be?

**Comment by Protowalker** [comment]
@Jordan-Ireland 2.0 preview has support for all of the new features. If you mean "when does the finished version come out," the answer is "soon, but not super soon."

**Comment by Jordan-Ireland** [comment]
@Protowalker When I tried importing code it said the Create Effect function wasn't correct. Since colors are selectable variables and can be RGB color values I think it messed it up. I even tried using an old project that was working pre-update (11/17/20) and it gave me an error.
