### ISSUE TITLE
Preview 2.0b Wait Async Not Functioning Properly

### ISSUE THREAD

**Issue by Jordan-Ireland** [ItsDeltin/Overwatch-Script-To-Workshop#223]
The Wait Async function seems to be firing immediately instead of waiting the allotted time. I even tried copy pasting the code provided in the Preview 2.0 release documents.

**Comment by Protowalker** [comment]
Can you add a repro?

**Comment by Jordan-Ireland** [comment]
@Protowalker I built from #221 with no changes. I can paste my .del code if you want. I'm away from computer for a few hours

**Comment by Protowalker** [comment]
You've built from source, then? Or are you using Preview 2b?

**Comment by Jordan-Ireland** [comment]
@Protowalker Sorry, I built from the source #227. I didn't know there was a difference in "Preview 2b" vs your working source.

**Comment by Protowalker** [comment]
@ItsDeltin I'm unable to test this on my system (I'm getting an exception when using WaitAsync). Are you able to look into it?

**Comment by ItsDeltin** [comment]
WaitAsync uses seconds rather than milliseconds. I would prefer it be milliseconds, but it is consistent with the workshop.
