### ISSUE TITLE
Using `0` in Vector compiles to `Empty Array`

### ISSUE THREAD

**Issue by timebomb0** [ItsDeltin/Overwatch-Script-To-Workshop#225]
Compiling `Vector(12, 0, 50)` compiles to `Vector(12, Empty Array, 50)`. This is on 2.0 Preview B. 0.0 is a valid vector location in some cases, so I'd expect it to compile 0 to the number 0 in this scenario.

**Comment by Protowalker** [comment]
Empty Array is equivalent to zero when used in the position of a number; this is an element optimization. If you don't want things like this to happen, you can disable it in the extension settings.

**Comment by TimeBomb** [comment]
Ahh ok, I didn't realize that was valid as a value in a vector. Thanks!

**Comment by timebomb0** [comment]
Ahh ok, I didn't realize that was valid as a value in a vector. Thanks!
