### ISSUE TITLE
Idea: Value methods (as opposed to Multiaction Value methods)

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#23]
When using something like this:
```
method PI()
{
    return 3.146;
}
```
it generates multiple actions when it only needs to paste the return line into the single action it is being used in.

Something like
```
define globalvar test;
rule:"test"
{
    test = PI();
}
```
instead returns
```
Set Global Variable At Index(A, 1, 3.146);
Set Global Variable At Index(A, 0, Value In Array(Global Variable(A), 1));
```
which uses an additional action where only 1 is needed.

**Comment by TrueCP6** [comment]
Maybe have different syntax for these kinds of methods that uses a different keyword and looks (as an example) like `shortcut PI() { return 3.146; }`. Just an idea.

**Comment by TrueCP6** [comment]
Methods with only a return value as seen above could be done in the same way as methods with the type "Value" within DeInteger.exe. They could also have a different syntax to allow more control. These kinds of methods would allow custom methods to be used in conditions, sorted and filtered arrays, etc.

The syntax could potentially look something like this:
```
value method ExampleMethod(input)
{
    return output;
}
```

**Comment by ItsDeltin** [comment]
Started this on the [macro branch.](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/tree/Macros)

**Comment by ItsDeltin** [comment]
Added in [v0.5.](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.5)
