### ISSUE TITLE
Potential infinite loop with switches when there is a syntax error.

### ISSUE THREAD

**Issue by ItsDeltin** [ItsDeltin/Overwatch-Script-To-Workshop#235]

**Comment by Protowalker** [comment]
Is this related to the memory leak experienced by Yurodd and Josbird?

**Comment by ItsDeltin** [comment]
Probably... the infinite loop will occur when `ParseStatement` doesn't progress the current token. The `Missing Element` node returned by it is constantly added to the switch's statement list resulting in a list of a few millions items after a while.
