### ISSUE TITLE
Unable to define arrays within methods

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#24]
Unable to specify that a variable needs to be separate from the main array of variables in methods unless I'm missing something.
`define directions = [Up(), Down(), Forward(), Right(), Backward(), Left()];` tries to create an array within a value of an array, and there is no way to set it as its own array within a method.

**Comment by AlexejheroYTB** [comment]
Can reproduce.

**Comment by AlexejheroYTB** [comment]
@ItsDeltin This is a very serious issue. Not being able to define arrays means that a lot of features cannot be used. Please look into this asap.

**Comment by AlexejheroYTB** [comment]
@TrueCP6 You can define your array outside of the method, then initialize it in the method

```
define globalvar directions Z;

//...

directions = [Up(), Down(), Forward(), Right(), Backward(), Left()];
```

**Comment by nathan130200** [comment]
I think ItsDeltin is ignoring all issue, i see in commit history, last commit in 10h ago, and he IGNORED ALL ISSUE IN REPOSITORY, i think that ItsDeltin don't known how to use a Github repository.

**Comment by AlexejheroYTB** [comment]
@nathan130200 Look at the previous issues. He replied to them. Look at his account. He has multiple repositories. HE KNOWS HOW TO USE A GITHUB REPOSITORY. SO SHUT UP AND LEAVE ALL OF US ALONE WITH YOUR SPAM COMMENTS

**Comment by nathan130200** [comment]
@AlexejheroYTB well no, he only have 6 repositories and this are only current maintained, so.... yes he is ignoring issues and pr's.

**Comment by TrueCP6** [comment]
I had to login with my phone to tell you how dumb you are. Guess what? Some problems are harder to fix than others. The closed issues tab exists.

**Comment by nathan130200** [comment]
@TrueCP6 I am not dump, fixing problems is simple if the code is not polluted, I did a pull request correcting the problem I had mentioned about the Wait. You have no arguments.

**Comment by TrueCP6** [comment]
You didn't even to bother to wait for a response to the pull request. You closed it yourself after 2 days. Not every one has all the time in the world like you to complain on some random repo on github. Maybe if you had some patience things would go better and your input would be used. Plus you spelt dumb wrong.

**Comment by AlexejheroYTB** [comment]
@ItsDeltin Please ban @nathan130200...

**Comment by TrueCP6** [comment]
> 
> 
> @TrueCP6 You can define your array outside of the method, then initialize it in the method
> 
> ```
> define globalvar directions Z;
> 
> //...
> 
> directions = [Up(), Down(), Forward(), Right(), Backward(), Left()];
> ```

You can do that but it can have issues when copy pasting methods.

**Comment by TrueCP6** [comment]
@ItsDeltin Please mark all the off topic comments as off topic

**Comment by AlexejheroYTB** [comment]
> > @TrueCP6 You can define your array outside of the method, then initialize it in the method
> > ```
> > define globalvar directions Z;
> > 
> > //...
> > 
> > directions = [Up(), Down(), Forward(), Right(), Backward(), Left()];
> > ```
> 
> You can do that but it can have issues when copy pasting methods.

What do you mean?

**Comment by ItsDeltin** [comment]
You can do `define directions L = [Up(), Down(), Forward(), Right(), Backward(), Left()];` inside methods.
Arrays still work doing `define directions = [Up(), Down(), Forward(), Right(), Backward(), Left()];`, it just doesn't show up in Overwatch's inspector.
Sorry it took me a while to get back to this issue.
