### ISSUE TITLE
Hero names with special characters unable to paste into overwatch

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#25]
Using `Hero.Lucio` and `Hero.Torbjorn` doesn't work when trying to paste into Overwatch. It results in an error message.

The code I used was `define globalvar testvar;
rule:"test"
{
	testvar = Hero.Torbjorn;
}`.

The output in vscode contains `Hero(Torbj�rn)` question mark and all which is probably the cause of the problem.

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.10](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.10).
