### ISSUE TITLE
"Index >= CountOf (Array) ? Array[CountOf (Array) - 1] : Array[Index]" return value is bool

### ISSUE THREAD

**Issue by Eruru3510** [ItsDeltin/Overwatch-Script-To-Workshop#26]

**Comment by Eruru3510** [comment]
The solution is "(Index >= CountOf (Array)) ? Array[CountOf (Array) - 1] : Array[Index]"

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.11](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.11)
