### ISSUE TITLE
'delete null' or 'delete 0' will cause the next class reference to be 0.

### ISSUE THREAD

**Issue by ItsDeltin** [ItsDeltin/Overwatch-Script-To-Workshop#261]

**Comment by Protowalker** [comment]
`delete 0` will no longer work on 2.0 because you can't delete the number type, but `delete null` will still not work. There might also be issues with the `Any` type, since it could be a number or a class

**Comment by ItsDeltin** [comment]
The same thing can be achieved doing this:
```
MyClass myVariable;
delete myVariable;
```
