### ISSUE TITLE
I copied overwatch-script-to-workshop to .vscode/extensions.

### ISSUE THREAD

**Issue by LeeIlJin** [ItsDeltin/Overwatch-Script-To-Workshop#28]
But, the 'Workshop Code' was not added to the output channel. :(

**Comment by TrueCP6** [comment]
Your file type should be .ostw or you should try going to extensions click the 3 dots and click install from vsix. The "Start Language Server.bat" must also be running with the correct ports selected.

**Comment by LeeIlJin** [comment]
![1](https://user-images.githubusercontent.com/35608190/60916302-f63f1900-a2c8-11e9-8a45-0764ed6865a0.png)
![2](https://user-images.githubusercontent.com/35608190/60916331-0951e900-a2c9-11e9-8da7-8bd045e1246f.png)
is it right?

![3](https://user-images.githubusercontent.com/35608190/60916423-40c09580-a2c9-11e9-84db-dfbac7af6859.png)
no 'workshop code' channel in output channels.

How can i get vsix file? i dont have.

**Comment by LeeIlJin** [comment]
![4](https://user-images.githubusercontent.com/35608190/60917260-82ead680-a2cb-11e9-9cd5-7733cfa5b768.png)
![5](https://user-images.githubusercontent.com/35608190/60917264-854d3080-a2cb-11e9-9936-d7ad9adcbb7c.png)

I tried packing vsix. but fail because that errors.
Is this the cause? So how do i solve this?

**Comment by ItsDeltin** [comment]
Its not compiling because you need to do `npm install` or something. The packed vscode extension is in the releases. There is a guide to install it on the bottom of the readme.

**Comment by LeeIlJin** [comment]
Thank You!!! :D

**Comment by nathan130200** [comment]
Using VSIX just run `vscode.exe --install-extension "path\to\extension.vsix"`
