### ISSUE TITLE
Incorrect argument type for AttachPlayers

### ISSUE THREAD

**Issue by sarami77** [ItsDeltin/Overwatch-Script-To-Workshop#284]
I using [v2.0-beta.10-win-x64].
The third argument type of AttachPlayers () is Vector. but incorrectly requested as Player() from compiler.
![snapshot](https://user-images.githubusercontent.com/63502714/106373537-d2b55500-63bd-11eb-9f0d-88d44a131f64.jpg)
![snapshot](https://user-images.githubusercontent.com/63502714/106373547-fd9fa900-63bd-11eb-8931-060b817dafbe.jpg)

**Comment by ItsDeltin** [comment]
For now you can cast by doing `<Player>(Up() * 3)`
Some more errors from the explicit changes:
- `RayCastHitPosition` missing `PlayersToInclude` default parameter.
- `Kill` missing `Killer` default parameter.
- `SetAllowedHeroes`'s `Hero` parameter's type is `Hero` rather than `Hero[]`

**Comment by ItsDeltin** [comment]
You can also fix it yourself by editing the `Elements.json` file in the server's installation folder, which should be at `C:\Users\User-Name\AppData\Roaming\Code\User\globalStorage\deltin.overwatch-script-to-workshop\Server`

**Comment by sarami77** [comment]
I've verified that the compilation resolves using the cast.
Thank you for your information.   :)

**Comment by ItsDeltin** [comment]
Fixed in v2.0-beta.11
