### ISSUE TITLE
Workshop Green Screen isn't a value

### ISSUE THREAD

**Issue by Preciseful** [ItsDeltin/Overwatch-Script-To-Workshop#285]
In the deathmatch mode (or any, haven't checked), workshop green screen isn't an option. 
![image](https://user-images.githubusercontent.com/73078691/106756879-642ffb80-6638-11eb-8264-700a27717ae2.png)
Attempted to solve by adding it in elements.json, wasn't successful.

**Comment by ItsDeltin** [comment]
Added in v2.0-beta.11
