### ISSUE TITLE
Idea: break re-evaluation on index in loops

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#29]
Having the option to create a variable that does not change like an index value would be extremely useful for creating large amounts of effects and icons in loops by keeping re evaluation but not re evaluating a specific variable.

**Comment by pielover928** [comment]
As in a variable that doesn't get reused after it's allocated the first time?

**Comment by TrueCP6** [comment]
Yeah exactly. It would be great for creating large amounts of re-evaluating
effects in loops while stopping the index variable from re-evaluating which
can create issues.

**Comment by pielover928** [comment]
Interesting. Very useful, yeah. You could use a "persistent" keyword, and then it would be as easy as checking a variable for that tag in the "garbage collector"

**Comment by ItsDeltin** [comment]
As far as I know, there isn't a way to do this other than the Event Damage workaround. The workshop devs may be looking into an official way of doing this.
