### ISSUE TITLE
New Beta Version of OSTW shows Element Count Limit of 20000

### ISSUE THREAD

**Issue by Syvul** [ItsDeltin/Overwatch-Script-To-Workshop#291]
I might setup the VS Code extension wrong, but i'an really confused the Element Count Limit shown by the extension is 20000, while the count got increased for the Workshop Editor back at some time. Is that intend? If not you mightwanna fix that little issue, thanks for your great project and work,!

**Comment by Protowalker** [comment]
Thanks for the heads-up :) will be fixed in the next version
