### ISSUE TITLE
About rounding option Nearest

### ISSUE THREAD

**Issue by LeeIlJin** [ItsDeltin/Overwatch-Script-To-Workshop#30]
![3](https://user-images.githubusercontent.com/35608190/61125311-78eff000-a4e4-11e9-8563-2bbe46cea601.png)
.del source
is ..
![1](https://user-images.githubusercontent.com/35608190/61125334-86a57580-a4e4-11e9-9514-50d8c609b051.png)
workshop code
but this code doesn't work

![2](https://user-images.githubusercontent.com/35608190/61125386-a3da4400-a4e4-11e9-91ee-8db25f235be7.png)
change 'Nearest' to 'To Nearest'

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.11](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.11)
