### ISSUE TITLE
Wait (ContinueSkip) format number incorrect.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#32]
In for/foreach loop is `Wait(0,016, Ignore Condition); // ContinueSkip Wait` but need to be `0.016` because workshop paste will throw error because workshop try parse `0` and `016` as function param.

Another issue: `Wait(0.025)` in script, results as `Wait(25)` in output:
![image](https://user-images.githubusercontent.com/14365254/61335864-6687f600-a805-11e9-9953-97f7798d12ed.png)

**Comment by nathan130200** [comment]
Due to git repo owner are IGNORING ALL ISSUE, i will close that.

**Comment by AlexejheroYTB** [comment]
Don't close the issue just because the owner is ignoring it. Keep it open. Maybe he is busy. He can't sit all day on github replying to issues.

**Comment by nathan130200** [comment]
Ok, i will leave open.

**Comment by nathan130200** [comment]
All double formats must be with CultureInfo.InvariantCulture, for users with different OS language than en-US will have problem with double formatting (some cases it insert comma instead of dot)

**Comment by nathan130200** [comment]
Another problem with `Wait` are if you set `Wait(0.025)` generated action is `Wait(25)` and this is wrong!!! The syntax don't convert 0.025 to 0.025 in Workshop, it convert 0.025 to 25....

**Comment by TrueCP6** [comment]
Why would you close an issue because someone doesn't sit on their ass checking issues on github all day

**Comment by nathan130200** [comment]
Last commit: 10 hour ago. He seen issue, just ignored.

**Comment by nathan130200** [comment]
😂 lol he uses Discord.Net 🤢🤢 now i see why the repository is this.

**Comment by TrueCP6** [comment]
He has probably seen it, but just because he hasn't replied doesn't mean he is ignoring it. You have to have serious entitlement issues if you think that anyone owes you a reply to anything. Especially if it doesn't need a reply. You must be fun at parties.

**Comment by Animadoria** [comment]
Why make the code open-source if you ignore any suggestions and errors? I mean, Nathan isn't wrong - it's a problem that needs to be solved. He already made the pull request, it's an easy thing to do, the owner just ignored.

**Comment by nathan130200** [comment]
Exactly!

**Comment by AlexejheroYTB** [comment]
@Animadoria @nathan130200 Just because he hasn't replied doesn't mean he's ignoring it. Look at all of the closed issues. He only replies to them once he's fixed them. So please stop.

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.12](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.12).
