### ISSUE TITLE
Numbers with more than 16 decimal places can't be imported into the Workshop

### ISSUE THREAD

**Issue by netux** [ItsDeltin/Overwatch-Script-To-Workshop#326]
Currently there is no clamping or rounding of very small decimal constant values, which causes the Workshop to error when parsing a number smaller than `1 / 10000000000000000`.
```
rule: "Rule"
{
  define a = 1 / 10000000000000000; // works
  define b = 1 / 100000000000000000; // throws error when importing: "Expected a value after: '0.00000000000000001'"
}
```

This is a problems, for example, when the Parser calculates numeric constants:
```
rule: "Rule"
{
  define RealisticGravityPerTick = 0.016 / -9.8; // throws error when importing: "Expected a value after: '0.00163265306122449'"
                                                 // removing the 9 at the end (either by clamping or rounding to the 16th decimal place) solves this issue.
}
```

**OSTW version:** v2.0-beta.14

**Comment by Protowalker** [comment]
I believe that I've already pushed a fix for this to master -- it should be in the next release :)
