### ISSUE TITLE
What should the syntax be for unparalleled structs?

### ISSUE THREAD

**Issue by ItsDeltin** [ItsDeltin/Overwatch-Script-To-Workshop#343]
## The problem

This struct will be used as an example.
```cs
struct Point
{
    public Number X;
    public Number Y;
}
```
Variables assigned with this data-type will have their workshop variables generated as so:
```cs
// ostw:
Point myPoint = {X: 5, Y: 6};

// workshop generated code:
global.myPoint_X = 5;
global.myPoint_Y = 6;
```
This has the advantage of avoiding arrays, which is known to be pretty good at hogging server load. There are 2 downsides to this approach, however:
- [Some array operations on structs are not supported](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/issues/342).
- Cannot be assigned to the 'Any' data-type.

## The solution

The solution to this is unparalleled structs, which store the struct data in an array. This is identical to how it structs worked pre-v1.0.

There needs to be a way to mark a struct type as unparalleled, for example, succeeding the type name with the `%` symbol:
```ts
// ostw:
Point% myPoint = {X: 5, Y: 6};

// workshop generated code:
global.myPoint = [5, 6];
```

**Comment by ItsDeltin** [comment]
Anonymous types cannot be assigned to the `Any` type for this reason, because it does not know if it may be a type. To solve this, type args can be marked as `single`, which will not accept parallel structs. Example:
```cs
void DoThing<single T>(in T value)
{
    Any assignToAny = value;
}

// Not okie dokie, adds a syntax error.
DoThing<Point>({X: 5, Y: 6});

// okie dokie
DoThing<Point%>({X: 5, Y: 6});
```

**Comment by CactusPuppy** [comment]
This has been resolved with the introduction of [single structs](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/wiki/Structs#single-structs)
