### ISSUE TITLE
Stop Holding Button takes two parameters in-game, but it says it only takes one parameter

### ISSUE THREAD

**Issue by netux** [ItsDeltin/Overwatch-Script-To-Workshop#35]
The definition it's just missing the button parameter.

![on VSCode](https://user-images.githubusercontent.com/6181929/61597186-978c7000-abe3-11e9-9883-709bf39cf13e.png)
I checked the executable to see if it was a problem with the VSCode extension, but it was not:
```
[:] Overwatch Script To Workshop v0.3.11
[:] Build Failed.
[:] Syntax error at 36, 34: The StopHoldingButton method takes 1 parameters, got 2 instead.
[:] Done. Press enter to exit.
```
Game clearly shows there is a button parameter:
![in game](https://user-images.githubusercontent.com/6181929/61597202-df12fc00-abe3-11e9-858c-be0a912fde77.png)

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.12](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.12).
