### ISSUE TITLE
[[0, 1], [2, 3]] creates a flat array like [0, 1, 2, 3].

### ISSUE THREAD

**Issue by ItsDeltin** [ItsDeltin/Overwatch-Script-To-Workshop#36]
Instead of a multidimensional array where [0] is [0, 1] and [1] is [2, 3].

**Comment by TrueCP6** [comment]
The only workaround I can think of for this would be a multiaction value custom method or one integrated into the [] syntax.

I don't think its possible to solve this without multiple actions.

**Comment by ItsDeltin** [comment]
No longer occurs with new `Array` value.
