### ISSUE TITLE
FilteredArray() of players fails to get type player.

### ISSUE THREAD

**Issue by Postur** [ItsDeltin/Overwatch-Script-To-Workshop#367]
My filtered array of players should have the GOLDminestatus variable of each player.
however here it is out of scope.
![image](https://user-images.githubusercontent.com/70761742/131269684-21d0b48e-f540-4141-abfe-92016a4cd94d.png)
My guess is the FilteredArray() method doesn't get the type from the first argument, and always returns an any type.
But in Overwatch this action is totally valid.

![image](https://user-images.githubusercontent.com/70761742/131269887-d6042741-2ff0-4e5e-992f-04144c79ac71.png)

How can I enforce a type?
 Thanks.

**Comment by Protowalker** [comment]
While we fix this bug, you can use typecasting as a workaround. If you have a value of one type and you want it to act like a value of another type, do `<OtherType>valueOfFirstType`

**Comment by Postur** [comment]
Thank you!
I also had to add ( ) to encase the type before accessing the value. 
Everything working as expected now :)

![image](https://user-images.githubusercontent.com/70761742/131929648-90976a70-2600-481c-a777-e8eb1b8ac78c.png)

**Comment by Protowalker** [comment]
Sorry for taking 4 days to respond! I didn't realize you had asked how you could enforce the type when I first read it.
