### ISSUE TITLE
No way to stop chasing a variable

### ISSUE THREAD

**Issue by netux** [ItsDeltin/Overwatch-Script-To-Workshop#38]
I noticed that, to solve the problem of `Chase Global/Player Variable At Rate/Over Time`, OSTW has a custom `Chase Variable()` method which takes a reference to a variable and manually updates it on a wait-loop.

I was digging around and couldn't find a way to stop chasing a variable that was started by that method.
Is it missing? Am I supposed to use `Stop Chasing Global/Player Variable()` somehow?

**Comment by ItsDeltin** [comment]
Chase the variable at 0 rate. I should make a built-in way to do it, though.

**Comment by ItsDeltin** [comment]
0.3.14 has `StopChasingVariable()`.
