### ISSUE TITLE
`Wait()` function `time` parameter incorrect description

### ISSUE THREAD

**Issue by singingwtrmln** [ItsDeltin/Overwatch-Script-To-Workshop#432]
**File**: @ItsDeltin/Deltinteger/Deltinteger/Wiki.xml

The `Wait(time)` description says that the minimum `time` value is **0.250** seconds, but it should reflect that this minimum is now **0.016** seconds, allowing for more frequent loops and checks.

_PS_: This is my first interaction on GitHub, sorry if I'm doing something wrong. I tried to see if someone else had posted this issue but didn't see anything.

**Comment by CactusPuppy** [comment]
I don't believe the `Wiki.xml` file is used for anything these days? I don't know, I could be wrong.
