### ISSUE TITLE
EventPlayer().SetProjectileSpeed() is not implemented or does not show up as a method option

### ISSUE THREAD

**Issue by kylelovestoad** [ItsDeltin/Overwatch-Script-To-Workshop#448]
Overwatch 2 allows for setting the projectile speed for the player

In workshop settings, this would look like this:
```python
Set Projectile Speed(Event Player, 50);
```

However attempting to use such a method when using the Player struct does not work. Instead, no option for this method is displayed, and trying to use it anyways says that it does not exist. This leads me to believe that it has not been implemented yet.

![image](https://user-images.githubusercontent.com/20408518/236720602-e1ebe664-cf75-4158-a22d-8aded7e10f3b.png)

This seems to be the case for other methods as well such as `Set Projectile Gravity()`

Thanks in advance! :)
kylelovestoad

**Comment by CactusPuppy** [comment]
@kylelovestoad `player.function` syntax only supports a subset of functions. It is possible to add them on our side, but in the meantime the intended OSTW syntax would be

```csharp
SetProjectileSpeed(EventPlayer(), 50);
```

As of the latest master build, this works for me; feel free to reopen this issue if you're unable to make the above work.
