### ISSUE TITLE
Genji is mispelled

### ISSUE THREAD

**Issue by TforTrevor** [ItsDeltin/Overwatch-Script-To-Workshop#45]
Genji in the Player enum is spelled as Gengi. It is also outputted as such and must be changed manually before pasting it into the workshop.
Genji is spelt correctly in the Hero enum.
![Capture](https://user-images.githubusercontent.com/36804391/63214986-e7c8f600-c0ed-11e9-9968-8f5061288509.PNG)

**Comment by ItsDeltin** [comment]
Thanks for the report! Fixed in [v0.3.15](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.15).
