### ISSUE TITLE
Debugger and constant enum expressions

### ISSUE THREAD

**Issue by pharingWell** [ItsDeltin/Overwatch-Script-To-Workshop#451]
Seems to not have the type ConstantEnumeratorExpression set up, but I have no idea what is needed to properly replicate the bug. It's my code interacting with the variables, for sure, but I cannot isolate it as of now. Here is the error in full

```OSTW debugger exception: System.Exception: Unsure of how to handle expression of type 'ConstantEnumeratorExpression'. at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.Error(String msg) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Debugger/Debugger.cs:line 134 at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.PartFromExpression(ITTEExpression expression) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Debugger/Debugger.cs:line 139 at System.Linq.Enumerable.SelectArrayIterator`2.ToArray() at Deltin.Deltinteger.Debugger.DebuggerActionSetResult.PartFromExpression(ITTEExpression expression) in /home/runner/work/Overwatch-Script-To-Workshop/Overwatch-Script-To-Workshop/Deltinteger/Deltinteger/Debugger/Debugger.cs:line 139 at Deltin.Deltinteger.Debugger.DebuggerActionSetResult..ctor(Workshop workshop) in /home/runner/work/Overwatch-Script-To-Workshop/...```

**Comment by CactusPuppy** [comment]
The debugger is deprecated and hasn't been updated in a long time, though admittedly it would be nice to have in OW2 what with the Inspector UI being broken for arrays since launch last year.
