### ISSUE TITLE
Unable to use any methods or access any variables within structs.

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#48]
When trying to use struct methods or variables within a rule, an error is detected and it does not compile into workshop code.
![Problem](https://i.imgur.com/3sLIwfT.png)
The problem is the same for struct methods.

**Comment by ItsDeltin** [comment]
Define the `players` variable like `Dictionary globalvar players;` instead of `define globalvar players;`
There is a bug right now where this won't work if the struct is on another file (with import) only for variables defined outside of methods.
