### ISSUE TITLE
Idea: Basic lambda expressions

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#49]

**Comment by TrueCP6** [comment]
This is also pretty similar to #52.

**Comment by ItsDeltin** [comment]
Started on the [Lambda](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/tree/Lambda) branch.

**Comment by ItsDeltin** [comment]
:tada: [v1.3](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.3)
