### ISSUE TITLE
Baptise does not have projectile gravity hero setting and attempting to decompile a custom game with the setting fails

### ISSUE THREAD

**Issue by SlenderFox** [ItsDeltin/Overwatch-Script-To-Workshop#492]
The custom settings json file does not have a projectile gravity setting for Baptise.
Trying to decompile a custom game with modified projectile gravity on Baptiste fails.
The custom game I tried to import also had a projectile gravity setting for Kiriko which failed to decompile, however I this setting does not appear in the Overwatch heroes settings menu (maybe it was removed?).

**Comment by CactusPuppy** [comment]
Fixed in #502
