### ISSUE TITLE
Use the same variable in multiple files

### ISSUE THREAD

**Issue by AlexejheroYTB** [ItsDeltin/Overwatch-Script-To-Workshop#55]

**Comment by AlexejheroYTB** [comment]
This generated variable is not defined errors in .ostw files

**Comment by TrueCP6** [comment]
Try saving the latest changes to the file you are referencing first before trying to use it.

It worked for me just fine:
![Defined variable](https://i.imgur.com/U2IScwf.png) ![No error](https://i.imgur.com/JzlBwQf.png)
