### ISSUE TITLE
Can't use variables in struct methods

### ISSUE THREAD

**Issue by pielover928** [ItsDeltin/Overwatch-Script-To-Workshop#70]
```
define hit = 45;
struct.Method(hit);
```

>variable "hit" is not defined.

**Comment by TrueCP6** [comment]
Use the `root` keyword to access outside-struct variables.

**Comment by ItsDeltin** [comment]
Fixed in [v0.6.](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.6)
