### ISSUE TITLE
Error: Encountered a value of an incompatible type after 'Text(' on line 96

### ISSUE THREAD

**Issue by AlexejheroYTB** [ItsDeltin/Overwatch-Script-To-Workshop#71]
Overwatch code:

![image](https://user-images.githubusercontent.com/32238504/66256441-7674fd80-e796-11e9-932e-44949329a779.png)

OSTW code:

![image](https://user-images.githubusercontent.com/32238504/66256445-868cdd00-e796-11e9-939c-7df79c84fb2b.png)

**Comment by ItsDeltin** [comment]
Looks like I messed up ternary conditional's priority again. Group the condition in parentheses like `(HeroOf(EventPlayer()) == Hero.Mccree) ? null : EventPlayer()`, internally it is being parsed like `HeroOf(EventPlayer()) == (Hero.Mccree ? null : EventPlayer())`

**Comment by AlexejheroYTB** [comment]
It works as intended now

**Comment by ItsDeltin** [comment]
Fixed in [v0.6.](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.6)
