### ISSUE TITLE
Append(array, value) not generating workshop actions.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#72]
# Description
I tried to create a list of vectors for spawn positions to my custom game.

# Steps to Reproduce

Deltinteger code:

```cs
define globalvar arr A;

rule: "set spawn positions"
{
	Append(arr, Vector());
	
	arr = Append(arr, Vector());
}
```

Output:

```cs
// --- Variable Guide ---
// global A[0] INTERNAL : Multidimensional Array Builder
// global A[1] INTERNAL : Class Indexes
// global A arr

rule("set spawn positions")
{

	event
	{
		Ongoing - Global;
	}
	
	// Action count: 1
	actions
	{
		Set Global Variable(A, Append To Array(Global Variable(A), Vector(0, 0, 0)));
	}
}
```

# Notes

The second line `arr = Append(arr, Vector());` ok, but first `Append` is missing. I think must be something like `Modify Global Variable(A, Append To Array, Vector(0, 0, 0));`

I known that deltinteger have `arr = [ ... ]` but create single line and too big action block.

**Comment by TrueCP6** [comment]
This is because `Append` is treated as a value within OSTW (not an action) and Overwatch. You can't use `Append` as an action within Overwatch. Use `array = [array, value(s) to append]` instead.

**Comment by ItsDeltin** [comment]
v0.6 fixed Append being used as an action not throwing a syntax error.
