### ISSUE TITLE
Foreach Bug

### ISSUE THREAD

**Issue by crskycode** [ItsDeltin/Overwatch-Script-To-Workshop#75]
My Script: [http://codepad.org/EN8QNA0D](url)
Line: 297
Map: Dorado
I try to create some effects with a loop (FOR or FOREACH), but some errors have occurred.
A global variable has changed by the loop in a method, the loop does not work.

**Comment by ItsDeltin** [comment]
If the positions of the effects will not update, change the reevaluation from `EffectRev.VisibleToPositionAndRadius` to `EffectRev.VisibleTo`. The foreach's internal index changes causing it to have the incorrect position. Do you need to update the death sphere's position?

**Comment by crskycode** [comment]
> If the positions of the effects will not update, change the reevaluation from `EffectRev.VisibleToPositionAndRadius` to `EffectRev.VisibleTo`. The foreach's internal index changes causing it to have the incorrect position. Do you need to update the death sphere's position?

Is the effect's position binding to a variable? If i need a effect class with dynamically position, how to do it?  They need to store in an array.

**Comment by ItsDeltin** [comment]
If you are just moving it every once in a while, destroy then recreate the effect at the new position. 
The other option is to check out [Container.del](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/blob/master/Examples/Bullets/Container.del). This can be used to break index re-evaluation, you can call it like:
```js
// Creating zone
ActivateScoper(1, new DeathZone(Vector(16.074, 1.722, -27.504), 3));
// Doesn't have to be directly with 'new'
ActivateScoper(1, ArrayOfDeathZones[i]);

rule: "Create effect without reevaluating internal class index"
Event.OnDamageTaken          // This works using event damage, which does not reevaluate.
if (scoper == EventPlayer())   // scoper is defined in Container.del
if (GetID() == 1) return;        // GetID should equal expected ID, which is the first parameter in the ActivateScoper method. This is useful for using the scoper for different things.
{
    CreateEffect(AllPlayers(Team.Team1), Effect.Sphere, Color.Red, scopedZone().Position, scopedZone().Radius, EffectRev.VisibleToPositionAndRadius);
}

macro scopedZone(): <DeathZone>GetData(); // GetData() is defined in Container.del
```


Related to #29
