### ISSUE TITLE
Cannot loop an array of struct correctly

### ISSUE THREAD

**Issue by Liu233w** [ItsDeltin/Overwatch-Script-To-Workshop#78]
see the code below:
```c#
struct TestClass
{
    public define num1;
    public define num2;

    public TestClass(define num1, define num2)
    {
        this.num1 = num1;
        this.num2 = num2;
    }
}

define globalvar arr T = [];

rule: "generate array"
{
    arr = Append(arr, new TestClass(0.1, 0.11));
    arr = Append(arr, new TestClass(0.2, 0.22));
    arr = Append(arr, new TestClass(0.3, 0.33));
    arr = Append(arr, new TestClass(0.4, 0.44));
}

rule: "show array"
{
    Wait(1);
    foreach (TestClass c in arr)
    {
        CreateHudText(AllPlayers(), <"<0>, <1>", c.num1, c.num2>);
    }
}
```
When the game started, it will output 8 huds(instead of 4), which means that the loop body is executed 8 times.

**Comment by TrueCP6** [comment]
I'm pretty sure structs are stored as arrays.`Append` flattens the 2 arrays you are trying to append to each other (#36). So the structs are effectively all merged into a single array with a length of 8. Instead set each element like `arr[0]`, `arr[1]`, etc. It also may be that you have to do `TestClass globalvar arr = [];` instead of defining normally.

**Comment by Liu233w** [comment]
Hi @TrueCP6 , thanks for your reply.

When I changed the array defination into `TestClass globalvar arr = [];`, it still outputs 8 huds (OSTW version 0.6). It is obvious that the compiler can find a way to restore the struct from a flatten array because the defination of the array and `foreach` loop shows the type of the struct.

**Comment by ItsDeltin** [comment]
He means appending the values like this instead:
```
arr[0] = new TestClass(0.1, 0.11);
arr[1] = new TestClass(0.2, 0.22);
arr[2] = new TestClass(0.3, 0.33);
arr[3] = new TestClass(0.4, 0.44);
```
Append will work with classes instead of structs because classes returns a reference rather than the array containing the struct.

**Comment by Liu233w** [comment]
hmmm, now I understand.
