### ISSUE TITLE
Idea: Attacker, Victim, EventPlayer and HostPlayer as value instead of method.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#79]
Replace Attacker, Victim, EventPlayer and HostPlayer, etc, as script value instead of method calling.

Examples
`Kill(eventPlayer)`
`Teleport(attacker, Vector(0,0,0))`

**Comment by ItsDeltin** [comment]
[v1.0-prerelease-1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.0) now supports parameter-less macros:
```
macro eventPlayer: EventPlayer();
macro attacker: Attacker();
macro victim: Attacker();
macro hostPlayer: HostPlayer();
```
