### ISSUE TITLE
Mistaking Array as Variable

### ISSUE THREAD

**Issue by halseyislife** [ItsDeltin/Overwatch-Script-To-Workshop#82]
`murderers[0].ents[6] = LastTextID();` is resulting in `Set Player Variable(Value In Array(Global Variable(murderers), 0), ents, Last Created Entity);` replacing the whole variable instead of just the index

**Comment by ItsDeltin** [comment]
If `murderers` is a class array do `(<Murderer>murderers[0]).ents[6]` instead, replace `Murderer` with whatever the class name is.

**Comment by ItsDeltin** [comment]
67933a573122580c0580a4264556355fe225e027 should fix it.
