### ISSUE TITLE
Idea: Extension communication and performance.

### ISSUE THREAD

**Issue by nathan130200** [ItsDeltin/Overwatch-Script-To-Workshop#83]
- Use websocket server communication with deltinteger and vscode extension to provide more speed and two-way data exchange.

- Reduce performance issues, for example an multi file script (using imports), take long time to compile and use high memory and cpu while compiling.

**Comment by ItsDeltin** [comment]
[v0.7](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.7) will no longer reparse every imported file when one change is made to one of them.

**Comment by nathan130200** [comment]
Thank you ❤️

**Comment by nathan130200** [comment]
Another thing, prevent deltinteger crash every time that syntax is incorrect or when typping code, forward message to vscode to warn user about wrong syntax.

**Comment by ItsDeltin** [comment]
The language server now uses io instead of tcp as of [v1.0-prerelease-1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.0).
