### ISSUE TITLE
Need more documents about formatted strings

### ISSUE THREAD

**Issue by Liu233w** [ItsDeltin/Overwatch-Script-To-Workshop#87]
I just tried to use localized string in the formatted string, but havn't found a way.

If I use the formatted string like `<@"server_load: <0>", ServerLoad()>`, an error is shown:
<details>

``` json
{
	"resource": "/d:/Sources/project/overwatch-doomfist-fight/snippets and experiment/debug formatted custom string.del",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Failed to parse the string \"@\"server_load: <0>\".",
	"startLineNumber": 3,
	"startColumn": 30,
	"endLineNumber": 3,
	"endColumn": 65
}
```
</details>

Did I do it wrong or OSWT doesn't support localized formatted string anymore?

**Comment by ItsDeltin** [comment]
That is a bug, which is fixed in v0.7.3.
