### ISSUE TITLE
ControlPoint* functions should be ControlMode*

### ISSUE THREAD

**Issue by synap5e** [ItsDeltin/Overwatch-Script-To-Workshop#89]
The functions `ControlPointScoringTeam` and `ControlPointScoringPercentage` do not exist in the OW workshop, and are instead named `ControlModeScoring...` i.e. 
![image](https://user-images.githubusercontent.com/2515062/69683810-fd9d7c80-111a-11ea-8cbe-08eb5f3ecda4.png)

The other `ControlMode` function `IsControlModePointLocked` is named correctly however.

**Comment by ItsDeltin** [comment]
Fixed in [v1.0-prerelease-1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.0).
