### ISSUE TITLE
If no connection to the wiki page can be established a null reference exception is thrown.

### ISSUE THREAD

**Issue by TrueCP6** [ItsDeltin/Overwatch-Script-To-Workshop#95]
If [the wiki page](https://us.forums.blizzard.com/en/overwatch/t/wiki-workshop-syntax-script-database/) is down (as it is while typing this) a null reference exception is thrown due to `Wiki.GetWiki()` returning `null`.

Edit: the wiki page is back up

**Comment by ItsDeltin** [comment]
The wiki is now stored locally in [v1.1](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.1).
