### ISSUE TITLE
Unsure how to make an Or condition equal to false

### ISSUE THREAD

**Issue by EnderHunterFTW** [ItsDeltin/Overwatch-Script-To-Workshop#97]
> rule: "StandardNavHud"
> Event.OngoingPlayer
> if(And(E, HasSpawned()))
> if(Or(Ep, Fp))
> {}

Can someone help me figure out how to make this or value equal false? (ep and fp are predetermined playervars)

**Comment by ItsDeltin** [comment]
Both of these should work:
`!Ep && !Fp`
`!(Ep || Fp)`
If you want to use Or instead of || for some reason:
`Not(Or(Ep, Fp))`
`!Or(Ep, Fp)`

**Comment by TrueCP6** [comment]
Additionally, if you have any other questions it's best to ask them in the #highlevel-scripting channel of [this discord](https://discord.gg/UPqcShn).
